name: Deploy to PythonAnywhere

on:
  push:
    branches: [ "main" ]  # ajusta si usás otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar deploy en PythonAnywhere por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh.pythonanywhere.com
          username: agustinmadygraf
          key: ${{ secrets.PA_SSH_KEY }}
          # Make sure PA_SSH_KEY is added in your repository's Settings > Secrets and variables > Actions > Repository secrets
          port: 22
          script: |
            bash ~/RasaBot/deploy.sh
